project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - info-for-students.qmd
    - info-for-sponsors.qmd
    - people.qmd
    - projects/*

website:
  page-footer: "Site content credit to Kathleen Coburn and Trevor Ruiz, created with Quarto. Hex logo by Priscilla Siow."
  google-analytics: "G-2RLZ4ZPF1B"
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197.github.io"
  sidebar:
    # title: "Data Science Capstone"
    style: "docked"
    collapse-level: 1
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - href: index.qmd
        text: Home
      - info-for-students.qmd
      - info-for-sponsors.qmd
      - people.qmd
      - section: "Projects"
        contents:
          - projects/projects-22-23.qmd
          - projects/projects-21-22.qmd
          - projects/projects-20-21.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# editor: visual

