---
title: "Information for students"
editor: visual
---

The goal of the capstone is to provide training in collaborative data science, hands-on research experience, and career development opportunities to students who are about to enter the job market or who are considering graduate school.

The capstone is designed primarily for **senior students** of any discipline having an intermediate level of experience with applied quantitative methods of any kind and some exposure to programming. It is **not** expected that students will have obtained any specialized background or completed advanced coursework prior to participating, and students from non-PSTAT major programs are encouraged to apply. Here you can find information on eligibility, how to apply, and program outcomes.

::: callout-note
## At a glance

-   60 seats available each year

-   Participation is **by application only**; applications open in Spring quarter for the following year, add codes will be distributed at the start of Pass 3 for the Fall quarter

-   Eligibility requirements:

    -   junior or senior standing by Fall quarter of the program year;

    -   strong academic record;

    -   motivation and interest in research;

    -   some prior experience with computing, statistics and probability, and regression

-   Students must make a **full year commitment** -- enroll in one 4-credit course each quarter -- to participate

-   Specialized or advanced training in statistical modeling, machine learning, computing, data science, etc. are beneficial, but are ***not required***
:::

## How to apply

Applications open in Spring quarter and remain open through summer. To apply, simply fill out the application form linked below (the form will be live while applications are open).

<!-- \[[Application form](https://docs.google.com/forms/d/e/1FAIpQLSe0tNoWXC9GKBHxhlqxRxq6Q61iQh0HW-sN_px5emVEphY4Fg/viewform?usp=sharing)\] -->

<!-- Applications will be reviewed beginning **August 1st, 2025** and on a rolling basis thereafter. An initial cohort will be notified by **September 9th, 2025** and will be provided with add codes for enrollment. Other applicants meeting eligibility requirements will be waitlisted, and any remaining seats will be allocated by mid-September prior to the start of the program year. Once all seats in the course have been filled, the application will be closed. -->

## What to expect

Students can expect to gain training and skills in collaborative data science and produce a strong work sample by the end of the program. All students will prepare a poster presentation for a public showcase of student work toward the end of the year. Posters will also be published online.

Depending on the project, students may also contribute during or after the project work period to other outputs such as public repositories, software products, conference presentations, or publications.

Besides project outputs, students receive mentorship from their project advisors throughout the course of the experiential learning component of the capstone. Students also gain access to the network of current and past participants and project sponsors for career development purposes.

## Prerequisites and eligibility

The prerequisites for the capstone are exposure to (1) computing, (2) statistics and probability, and (3) regression. Since the program is interdisciplinary and intended to be accessible to non-PSTAT majors, these requirements are not strictly tied to any specific courses.

For the PSTAT student, completion of regression analysis (PSTAT126) should suffice. For the non-PSTAT student, any prior experience with statistical concepts, quantitative models, and computing will be considered.

Students should be of junior or senior standing by the term they would begin the capstone (*i.e.,* Fall of the year of application). A **full-year commitment** is expected to participate, so seniors expecting to graduate early may not be eligible; students who are able to commit to enrolling in all three courses will be prioritized for admission. Younger students, even if otherwise eligible, will be encouraged to reapply in a later year.

Students should have a strong academic record and be motivated to learn independently and work on a research problem.

## FAQ

*How are students selected for enrollment in the class?*

Applications are screened to ensure participation requirements are met: completion of prerequisites, good academic record, and junior or senior standing. Among students who meet these participation requirements, applications will be reviewed by a committee and evaluated based on their sample of prior work and their motivation for application to the program. 

*Is there a GPA requirement?*

Your GPA does contribute in determining eligibility to participate (a higher GPA corresponds to a better academic record), but there is not a hard cutoff.

*Are there any specific languages/packages I need to know?*

No. The requirement is that you have intermediate proficiency (use in 2+ courses or equivalent) in *some* language so that you are familiar with programming concepts and able to learn further skills semi-independently (*i.e.,* with the help of a book or tutorial). Most students will have had some experience with R or Python, and some with similar languages such as Matlab, Mathematica, or Julia. However, what constitutes 'experience' is pretty broad, and can range from a few courses to a few years of use. Regardless of experience, almost everyone will develop new programming skills 'on-the-job' in the course of their projects. All projects are different and students do not need a specific background to succeed.
s
*Are there any recommended classes that would prepare me for the capstone?*

CMPSC 5A-B and PSTAT 100 are widely accessible data science courses that can be taken in sequence over the course of a year and generally will provide good preparation for the capstone and exposure to programming in Python. PSTAT students may elect to take the statistical learning course (PSTAT 131) for additional preparation. Non-PSTAT majors would benefit from any quantitative methods courses offered in their home department. More broadly, any course(s) that reinforce programming skills and data analysis will be beneficial.

*How are students assigned to capstone projects in the program?*

Students have the opportunity to review proposed project abstracts and specify a set of preferred assignments. Preferences are considered together with technical skills, domain backgrounds, and factors affecting group dynamics in forming project teams, so **we cannot guarantee students will receive their top choices**. Ultimately, project assignments are made at the discretion of instructors.

*Will I get a job or internship through the program if my project is successful?*

This is not guaranteed. Project sponsors' commitments conclude at the end of the academic year. In some instances, sponsors have the resources and interest to support summer interns or entry-level hires, but this is entirely at their discretion. We have had students recruited in the past this way, but they comprise a minority of all program participants.
