---
title: 'People'
---

::: callout-note
## Contacts for 2025-2026 capstone

-   Anthony W. Coburn, lecturer and capstone instructor: project mentorship and course information for 2025-2026 \[[email](mailto:tony_w_coburn@ucsb.edu)\]

- Sang-Yun Oh, associate professor: business liason, computational resource contact \[[email](mailto:syoh@ucsb.edu)\]

-   Jessie Priestley: program oversight, direction/coordination, marketing, funding management \[[email](mailto:jlp@ucsb.edu)\]
:::

*Participants listed by year, in alphabetical order by last name.*

## 2025-2026

### Instructor

*Dr. Anthony (Tony) Coburn,* Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

### Project mentors
(in alphabetical order by last name)

TBD

### Project advisors
(in alphabetical order by last name)

-   *Tony Coburn,* Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

-   *Yan Lashchev,* Undergraduate Program Advisor, Statistics

## 2024-2025

### Instructors

*Dr. Laura Baracaldo,* Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

*Dr. Kathleen Coburn,* Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

### Project mentors

-   *Michaela Alksne*, UCSD Scripps Institute of Oceanography

-   *Lucas Boyd*, UCSB Political Science / 2035 Initiative

-   *Laura Harrison*, UCSB Climate Hazards Center

-   *Larissa Heeren*, SLO County Probation Dept.

-   *James O'Brien*, SoundEthics

-   *Erin Satterthwaite*, CalCOFI

-   *Katja Seltmann and Maddie Oswald*, CCBER

-   *Shraddhanand Shukla*, Geography Department

-   *Michael Schmidt and Yvonne Baur*, NationBuilder

-   *Derek Mendez*, SLAC National Accelerator Laboratory

### Project advisors

-   *Dr. Laura Baracaldo,* Visiting Assistant Professor, Statistics

-   *Dr. Kathleen Coburn*, Lecturer, Statistics

-   *Yan Lashchev,* Undergraduate Program Advisor, Statistics

-   *Jose Nino,* DREAM Lab

-   *Erika McPhillips,* PhD Student, Statistics

-   *Dr. Avani Tanna,* Lecturer, Computer Science

-   *Jeffrey Wu*, PhD Student, Statistics

### Students

-   Leena-Karima Anqud 

-   Anshi Arora

-   Liuqian Bao

-   Bennett Bishop

-   Xiaofeng Cai

-   Rebecca Chang

-   Christina Hefan Cui

-   Keon Dibley

-   Luke Dillon

-   Jiajia Feng

-   Valerie de la Fuente

-   Tess Ivinjack

-   Amy Ji

-   Ruizhe Jiang

-   Reese Karo 

-   Nikhil Kuniyil

-   Justin Lang 

-   Daniel Ledvin

-   Ivy Li

-   Casey Linden

-   Navin Lo

-   Kuan-I Lu

-   William Mahnke

-   Nazhah Mir

-   Sophia Mirrashidi

-   Jade O'Brien

-   Owen Philliber

-   Sean Reagan

-   Parker Reedy

-   James San

-   Pramukh Shankar

-   Kasturi Sharma

-   Sophie Shi

-   Jiaxin Su

-   Shirley Wang 

-   Joseph Zaki

-   Wentao Zhang

## 2023-2024

### Instructor

*Dr. Laura Baracaldo,* Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

### Project mentors

-   *Jordan Tran,* Appfolio

-   *Nate Emery,* CITRAL

-   *Michaela Alksne,* Scripps Institution of Oceanography

-   *Katja Seltmann,* CCBER

-   *Shraddhanand Shukla,* Climate Hazards Center, Geography Department

-   *Michael Schmidt,* Nation Builder

-   *Matto Mildenberger,* Political Science Department

-   *Eric Leidersdorf,* P3

-   *Derek Mendez,* SLAC National Accelerator Laboratory

### Project advisors

-   *Dr. Laura Baracaldo,* Visiting Assistant Professor, Statistics

-   *Dr. Alex Franks,* Assistant Professor, Statistics

-   *Yan Lashchev,* Undergraduate Program Advisor, Statistics

-   *Jose Nino,* Data Science Student Advisor, Computer Science

-   *Erika McPhillips,* PhD Student, Statistics

-   *Dr. Avani Tanna,* Lecturer, Computer Science

### Students

-   Aaron Lee  

-   Aarya Kulkarni  

-   Amber Wang  

-   Amy Lyu  

-   Ashwath Ekambaram  

-   Ayushmaan Gandhi  

-   Chris Zhao  

-   Christopher Straw  

-   Claire Lee  

-   Dannah Golich  

-   David Lin  

-   Dylan Fu  

-   Erica Chen  

-   Griffin Sheppard  

-   Haoran Yan  

-   Irena Wong  

-   Jackie Chen  

-   Jade Thai  

-   Jennifer Rink  

-   Jiashu Huang  

-   Jinran Jin  

-   Jimmy Dysart  

-   Kayla Katakis  

-   Kyle Wu  

-   Manuri Alwis  

-   Mario Tapia-Pacheco  

-   Matthew Lee  

-   Mindy Xu  

-   Molata Fu  

-   Mu Niu  

-   Navneet Rajagopal  

-   Pippa Lin  

-   Patrick Moon  

-   Peng Zhao  

-   Rohit Kavuluru  

-   Rohan Anand  

-   Ryan Sevilla  

-   Sanaz Ebrahimi  

-   Sarah Liang  

-   Sharanya Sharma  

-   Sharon Lee  

-   Shuai Yuan  

-   Sichen Zhong  

-   Yibo Liang  

-   Yijiao Wang  

-   Zoe Zhou  

## 2022-2023

### Instructor

*Dr. Trevor Ruiz*, Statistics and Applied Probability (PSTAT197A-B-C/CMPSC190DD-DE-DF)

### Project mentors

Maxim Ivanov and Bonnie Jin, Amgen

Ari Polakof, Appfolio

Erin Satterthwaite, California Cooperative Oceanic Fisheries Investigations

Andy Chen and Amy Huynh, Carpe Data

Eleanor Caves and Todd Oakley, Caves Visual Ecology Lab

Katja Seltmann, Cheadle Center for Biodiversity and Ecological Restoration

Greg Husak and Shrad Shukla, Climate Hazards Center

Patrick Green, Evolutionary Ecology and Marine Biology

Norbert Leinfellner and Paula Sarmiento, Inogen

Arinbjörn Kolbeinsson and Eric Daza, Evidation Health

Somayeh Dodge and Evgeny Noi, MOVE Lab

Eric Leidersdorf, Peak Performance Project

Derek Mendez, Stanford National Accelerator Lab

### Project advisors

Dr. Trevor Ruiz, Statistics and Applied Probability

Dr. Alex Franks, Statistics and Applied Probability

Dr. Laura Baracaldo, Statistics and Applied Probability

Dr. Adam Waterbury, Statistics and Applied Probability

Enbo Zhou, Geography

Erika McPhillips, Statistics and Applied Probability

Joshua Bang, Statistics and Applied Probability

Megan Elcheikhali, Statistics and Applied Probability

Robin Liu, Statistics and Applied Probability

Gia Ahn, Statistics and Applied Probability

Yan Lashchev, Statistics and Applied Probability

### Students

Safiya Alavi, STSDS

Daniel Badilla, STSDS

Ellie Burrell, STSDS

Brian Che, STSDS

Aleksander Cichosz, ECON/STSDS

Fei Du, AMATH/STSDS

Brian Fan, AMATH/STSDS

Kunxiao Gao, STSDS

Bernie Graves, STSDS

Yuer Hao, FINMS

Disha Hauzaree, STSDS

Edward Ho, STSDS

Evan Ji, STSDS

Dingan Jiang, ECON/STSDS

Aria Kajeh, STSDS

Raymond Lee, PBS/STSDS

Hannah Li, STSDS

Lily Li, STSDS

Yujie Li, STSDS/LING

Alex Lim, STSDS

Justin Liu, STSDS

Tianhong Liu, FINMS

William Long, STSDS

Anya Macomber, STSDS

Ankur Malik, STSDS

Vardan Martirosyan, MATCS

Lex Navarra, STSDS

Jennifer Park, ECACC/STSDS

Mira Patel, STSDS

Ryan Quon, STSDS

Allester Ramayrat, STSDS

Giselle Ramirez, ENVST/POLS

Noa Rapoport, STSDS

Eitan Rashkovan, STSDS

Kaylin Roberts, STSDS

Shannon Rumsey, STSDS

Nealson Setiawan, STSDS

Thomas Shi, ACTSC

Kabir Snell, STSDS

Ashley Son, STSDS

Sofia Spasibenko, STSDS

Ryan Stofer, AMATH/STSDS

Sammy Suliman, AMATH/STSDS

Kassandra Trejo-Zamora, STSDS

Piero Trujillo, STSDS

Lyndsey Umsted, STSDS

Jai Uparkar, STSDS/CPTCS

Justin Vo, ECACC/STSDS

Ruoxin Wang, STSDS

Yuqing Xia, STSDS

Changhee Yoon, STSDS

Teo Zeng, PBS/AMATH

Chunting Zheng, AMATH/STSDS

Haoming Deng, STSDS

Caroline He, BIOCS

Dan Le, CMPSC

Allen Wang, STSDS

## 2021-2022

### Instructors

Dr. Ambuj Singh, Computer Science (PSTAT197A/CMPSC190DD)

Dr. Alex Franks, Statistics and Applied Probability (PSTAT197B-C/CMPSC190DE-DF)

Dr. Trevor Ruiz, Statistics and Applied Probability (PSTAT197B-C/CMPSC190DE-DF)

### Project mentors

Chad Spensky and Rita Mounir, Allthenticate

Shyr-Shea Chang and Soeren Thust, Appfolio

Erin Satterthwaite, California Cooperative Oceanic Fisheries Investigations

Crystal Zhang and Kevin Neal, Carpe Data

Qing Huang, Center for Information Technology Research

Katja Seltmann, Cheadle Center for Biodiversity and Ecological Restoration

Kelly Caylor, Anna Boser, and Ryan Avery, Earth Research Institute

Matto Mildenberger, Energy and Environment Transitions Lab

Eric Daza, Evidation Health

Rob Fox and Lauren Wong, HG Insights

Stella Glasauer, Neuroscience Research Institute

Rebert Bernard, Pricewaterhouse Coopers

Tommy Sprague, Sprague Lab

### Project advisors

Dr. Trevor Ruiz, Statistics and Applied Probability

Dr. Alex Franks, Statistics and Applied Probability

Dr. Adam Waterbury, Statistics and Applied Probability

Leron Reznikov, Computer Science

Sikun Lin, Computer Science

Erika McPhillips, Statistics and Applied Probability

Joshua Bang, Statistics and Applied Probability

Megan Elcheikhali, Statistics and Applied Probability

### Students

Annie Adams, STSDS

Nicholas Alexander, STSDS

Joshua Alvarado, STSDS

Akshat Ataliwala, STSDS

Andrew Bissell, STSDS

Evan Bui, STSDS

Philip Carey, STSDS

Eric Cha, STSDS

Tristan Chen, STSDS

Tyler Chia, STSDS/ECON

Dante Coletta, STSDS

Anum Damani, STSDS

James Du, PHYS/STSDS

Romina Fareghbal, STSDS

Emma Franzblau, POLS

Ian Gascon, FINMS/ECON

Atherv Gole, STSDS

Mallika Gupta, FINMS

Joshua Harasaki, STSDS

Eoin Hayes, STSDS

Annie Huang, LING/STSDS

Harleen Kaur, ECON/STSDS

Alyssa Keehan, STSDS

Joanne Kim, STSDS

Harper Klauke, STSDS

Mac Kul, STSDS

Jasmine Kwok, COMM/STSDS

Michael La, STSDS/ECON

Yan Lashchev, AMATH

Natasha Leodjaja, STSDS

Connor Levenson, STSDS

Jorge Murillo, MATCS

Jessica Nguyen, STSDS

Nathan Roll, ECON/LING

Alex Rudolph, STSDS

Sarah Schlund, STSDS/GEOG

Priscilla Siow, STSDS

Xavier Speropoulos, STSDS

Jordan Tran, STSDS

Ali Vakilimafakheri, STSDS

Rithvik Vobbilisetty, STSDS

Eric Wang, STSDS

Jonathan Wong-Lau, ACTSC

Yuki Yamazaki, STSDS

Johnny Yu, STSDS

Nancy Zha, STSDS

Yangyi Zhang, MTHSC/STSDS

Bosco De Enrique Romeu, UNDE

Teresa Gonzalez, GEOGP

Ashley Grinstead, ENVST/GEOGP

Tiffany Hsu, ENVST

Qiru Hu, CMPSC

Calvin Jenkins, CMPEN

Pk Kottapalli, PHYS

Sara Mandic, CMPSC

Elise Nguyen, COMM/ECACC

Lucas Nguyen, CMPSC/CMPSC

Jake Stenger, CPTCS

Lawrence Su, EE

Timi Tao, STSDS

## 2020-2021

### Instructors

Dr. Ambuj Singh, Computer Science (PSTAT197A/CMPSC190DD)

Dr. Alex Franks, Statistics and Applied Probability (PSTAT197B-C/CMPSC190DE-DF)

Dr. Sang-Yun Oh, Statistics and Applied Probability (PSTAT197B-C/CMPSC190DE-DF)

### Project mentors

Peng-Yuan Lai and Soeren Thust, Appfolio

Erin Satterthwaite, California Cooperative Oceanic Fisheries Investigations

Crystal Zhang, Carpe Data

Lubi Lenaburg, Center for Science and Engineering Partnerships

Katja Seltmann and Michelle Lee, Cheadle Center for Biodiversity and Ecological Restoration

Eric Daza, Evidation Health

Louis Tremblay, FLIR

Mike Lawrence, Invoca

Julien Brun and Allison Horst, National Center for Ecological Analysis and Synthesis

Juliana Acosta Uribe and Ken Kosik, Neuroscience Research Institute

Namino Glantz and David Kerr, Sansum Diabetes Research Institute

### Project advisors

Dr. Ambuj Singh, Computer Science

Dr. Mike Ludkovski, Statistics and Applied Probability

Dr. Sang-Yun Oh, Statistics and Applied Probability

Dr. Alex Franks, Statistics and Applied Probability

Kate Kharitonova, Computer Science

Sikun Lin, Computer Science

Joshua Bang, Statistics and Applied Probability

Jiajing Zheng, Statistics and Applied Probability

Chau Tran, Statistics and Applied Probability

### Students

Nick Bachelder, STSDS

Angel Chen, STSDS

Amy Cho, ECON/STSDS

Robin Hollingsworth, STSDS/ECACC

Zoe Holzer, STSDS

Joanna Kim, STSDS

Karsyn Lee, STSDS

Adhitya Logan, STSDS

Andrew Nguyen, STSDS

Nicholas Nunes, STSDS

Vikram Pasupathy, CMPSC/STSDS

Lia Ran, STSDS

Mitchell Rapaport, AMATH/STSDS

Cristian Razo, STSDS/PRMTH

Jake Simon, STSDS

Samantha Solomon, FINMS

Sophia Sternberg, COMM/STSDS

Shuyun Tang, STSDS

Gavin Tieng, STSDS

Romtin Toranji, STSDS

Meng Vong, STSDS

Jason Yu, STSDS

Karen Zhao, STSDS/ECACC

Andrea Anez, CMPEN

Priyanka Banerjee, CMPSC/STSDS

Peter Bayerle, AMATH

Karanveer Benipal, CMPSC

Matthew Coleman, STSDS

Cibran De La Fuente, PHIL/LING

Shuyi Fang, LING/GERM

Sam Guo, FINMS/CMPSC

Helen Huang, CMPSC/PHRMA

Shaka Kanenobu, CMPSC

Saiprem Kathika, CMPEN

Lawrence Lin, STSDS

Manny Medrano, EE/PRMTH

Shivam Misra, PHYS

Sairisheek Muttukuru, CMPEN

Priya Padmanabhan, CMPSC

Jay Patwardhan, AMATH

Ari Polakof, CMPSC/STSDS

Surya Pugal, CMPSC

Austin Quinn, CMPSC

Leron Reznikov, CMPSC

Andie Rupprecht, GEOGP

Neil Sadhukhan, CMPEN

Vanessa Salgado Zavaleta, CMPSC

Emily San Juan, PRMTH

Samuel Sheridan, AMATH/STSDS

Matthew Xu, STSDS

Rey Yue, CMPSC

Bill Zhang, CMPSC
